
###
POST http://localhost:5244/api/auth/register 
Content-Type: application/json

{
    "username": "johndoe",
    "email": "johndoe@example.com",
    "password": "password123"
}

###
POST http://localhost:5244/api/auth/login
Content-Type: application/json

{
    "email": "johndoe@example.com",
    "password": "password123"
}

###
GET http://localhost:5244/api/auth/refresh
Content-Type: application/json
Cookie: refresh_token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJKd3RTdWJqZWN0IiwianRpIjoiYjdhOWU5NTUtOTI0Yy00NGMzLWI0ZjAtYjJiZmI2MTE5N2RkIiwiVXNlcklkIjoiNjZjNzRiN2JiMzZjZTFlOTg3NjY2OWFiIiwibmJmIjoxNzI0NjYwOTE1LCJleHAiOjE3MjUyNjU3MTUsImlzcyI6Ikp3dElzc3VlciIsImF1ZCI6Ikp3dEF1ZGllbmNlIn0.YHt0cSYU86NdZ9OyN4W9XpthrbOv1V_Uu5kpFZoS6Cg

###
GET http://localhost:5244/api/books
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJKd3RTdWJqZWN0IiwianRpIjoiMDU0NDI1ZTQtMjFiNS00YjYzLThhNjMtMDc5MDk0YzY1NGUwIiwiVXNlcklkIjoiNjZjNzRiN2JiMzZjZTFlOTg3NjY2OWFiIiwiRW1haWwiOiJqb2huZG9lQGV4YW1wbGUuY29tIiwiZXhwIjoxNzI0NDMxNjQ5LCJpc3MiOiJKd3RJc3N1ZXIiLCJhdWQiOiJKd3RBdWRpZW5jZSJ9.eNecifdovy83Qh-_OG1XAR3lQRTtVyxi__IbRYc63Wc



###
GET http://localhost:5244/api/todo
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJKd3RTdWJqZWN0IiwianRpIjoiMDU0NDI1ZTQtMjFiNS00YjYzLThhNjMtMDc5MDk0YzY1NGUwIiwiVXNlcklkIjoiNjZjNzRiN2JiMzZjZTFlOTg3NjY2OWFiIiwiRW1haWwiOiJqb2huZG9lQGV4YW1wbGUuY29tIiwiZXhwIjoxNzI0NDMxNjQ5LCJpc3MiOiJKd3RJc3N1ZXIiLCJhdWQiOiJKd3RBdWRpZW5jZSJ9.eNecifdovy83Qh-_OG1XAR3lQRTtVyxi__IbRYc63Wc

###
GET http://localhost:5244/api/todo/1
Authorization: Bearer CfDJ8DgIlW363wFJtzWmx_ZxRRTdPybNwYcHxGXFcI_RHcxiKTrxphCqIt2iLAFpcBlq5uqP0qbMdURyyzxOGlX8V92GLlrQuQQG97_7_Qs5Q4kQt3GUnc9WTvj-PlnhWfsoEb9cobgr9WpCLBREJxWJe1Z4YalOp0ze0FFoLw0a1RVHCOOfOCin2tc2qfiE5apxG4M_J_C5Tx4iWHM23fT1y8-OUxsxBc7tBaYT1GSvS4LS71d8DK-TtLBul6ZG3-upXv2dJ6Y5DN3Bn22yDEqPjoBdUR9VGhMqwFDl3MzlPTBD2SRpZNwCqpbmrUynqSxsjQS3_cCm_oYQMzfWHKbn3tOQXYLXJq2oXxxLXflU8iGjIr-CCikLV6wnOKtSOkn12TnHO8QvXxNfsnUblgELPOBpPc7zmxuzRfcyx4mkhbIQUwaEVoG1VtQ0z9b0sV-8TUcZySSgJVtctED9HTdR3p8mTQwRVFByCyjYUKJSlFUXwvVYXcRcHAoqFIpVu9zTiMa4JbOxQbIkbjI_ELHJBXyy6VNmUFW8LFhKG7Bc2KZm6Zx5ebhUNwBCwf01gViVyNBy1kGJaEp2lHgml7kB1QqNmmva6D7_WlkidKzGnaEHLe5HNXwxJnXVl9rHN-SIt_bjBrre1j9df3fP7-DioKMUc97BYhTx3maIxQ8e3saIa5WdXlLnxtzK0bIRILXGYnioE6jWTXt1wsjENPTTrkM_tY3OPJQTJH4lOnIvtQGZ

###
POST http://localhost:5244/api/todo
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJKd3RTdWJqZWN0IiwianRpIjoiOWFmODJiYTAtYWM5NC00N2I2LWE0NWQtZDJkNjJlMmI2M2MwIiwiVXNlcklkIjoiNjZjNzRiN2JiMzZjZTFlOTg3NjY2OWFiIiwiRW1haWwiOiJqb2huZG9lQGV4YW1wbGUuY29tIiwiZXhwIjoxNzI0MzQ2ODkwLCJpc3MiOiJKd3RJc3N1ZXIiLCJhdWQiOiJKd3RBdWRpZW5jZSJ9.-nujyq_gGDufFMblxq0m2L-YDcNcD65RP_KOx2Rnuxg
Content-Type: application/json

{
    "description":"Go to LUNCH",
    "isCompleted":false
}
###
PUT http://localhost:5244/api/todo/26
Authorization: Bearer CfDJ8DgIlW363wFJtzWmx_ZxRRTdPybNwYcHxGXFcI_RHcxiKTrxphCqIt2iLAFpcBlq5uqP0qbMdURyyzxOGlX8V92GLlrQuQQG97_7_Qs5Q4kQt3GUnc9WTvj-PlnhWfsoEb9cobgr9WpCLBREJxWJe1Z4YalOp0ze0FFoLw0a1RVHCOOfOCin2tc2qfiE5apxG4M_J_C5Tx4iWHM23fT1y8-OUxsxBc7tBaYT1GSvS4LS71d8DK-TtLBul6ZG3-upXv2dJ6Y5DN3Bn22yDEqPjoBdUR9VGhMqwFDl3MzlPTBD2SRpZNwCqpbmrUynqSxsjQS3_cCm_oYQMzfWHKbn3tOQXYLXJq2oXxxLXflU8iGjIr-CCikLV6wnOKtSOkn12TnHO8QvXxNfsnUblgELPOBpPc7zmxuzRfcyx4mkhbIQUwaEVoG1VtQ0z9b0sV-8TUcZySSgJVtctED9HTdR3p8mTQwRVFByCyjYUKJSlFUXwvVYXcRcHAoqFIpVu9zTiMa4JbOxQbIkbjI_ELHJBXyy6VNmUFW8LFhKG7Bc2KZm6Zx5ebhUNwBCwf01gViVyNBy1kGJaEp2lHgml7kB1QqNmmva6D7_WlkidKzGnaEHLe5HNXwxJnXVl9rHN-SIt_bjBrre1j9df3fP7-DioKMUc97BYhTx3maIxQ8e3saIa5WdXlLnxtzK0bIRILXGYnioE6jWTXt1wsjENPTTrkM_tY3OPJQTJH4lOnIvtQGZ
Content-Type: application/json

{
    "isCompleted":true
    
}
###
DELETE  http://localhost:5244/api/todo/3
Authorization: Bearer CfDJ8DgIlW363wFJtzWmx_ZxRRSGb3BhM9nJ4A9wcT37g4RXU6edvu41dBgS8pWAU9SyRzw69Sp9NJ-QHqv5RS0nA0wzhbfeUlTc42rYuUt1v8StUd1kWOWjBzTAbUrn-PdJChthTAhEtqbYmypUqbq0RP3zXeYppnE57vYPjoUjkODzQqxrKovS30JYnu3tlFsLwzAUDeetprsiOdvuCHCkvxxYXy7_9D8PDe7hEmLay2eSekba3ZPdAsUN9r-0iF_SEnKoruz8typvj9nadXvzczVBpNAWCoG8z_2gqsExisHqCg4E3l7az0lzU-2Z1dV7ELxdc3JSeUAGzOlhdqstATDNdNYyyUnfkqCk78z5ywgj-PUa4EfpxcpX2m-_URrNlj45JFYcha5QQKV1m4U_DU_4ywaWZiyAaohxtigYuOJzRMO3i_W569b3lsjXfesyOBswZOeUrZPxk_6vRwCwETkl5Z8MRezbgsKp195DcNkZs7zXu6GhgBSgs4ZnD2E1U9E_dKa0sxZ2lVmdpsudW2QvktcBHIEf5YwMVYCz86p_E2IfpSvmkiBafqUPIJo_V3rbgW0slvlQEmqhsWelOobOfIS3kj-anPprPQqlw2VfJYSVpWtt36VjgXD2fTeo_8v5-wMvb093ojdPQ1I6OuE
